# Use an official Node.js runtime as the base image
FROM node:20 AS build

# Set the working directory
WORKDIR /app/proj-1/client

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY . .

# Build the React application
RUN npm run build

# Use an official Nginx image to serve the application
FROM nginx:1.25

# Copy the build folder to the Nginx default directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 3000

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
